name: Build Wheels

on:
  push:
    branches: [main]
    tags: ["v*", "dev*", "try*"]

env:
  PYTHONIOENCODING: utf-8
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PyPI }}

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python_version: ['3.7', '3.8', '3.9', '3.10']
        python_architecture: ['x86', 'x64']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cargo check
        run: cargo check --verbose
      - name: Cargo test
        run: cargo test --verbose
      - name: setup python
        uses: actions/setup-python@v4
        id: cpy
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.python_architecture }}
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: python -m pip install twine maturin
      - name: Build python wheels
        run: python -m maturin build --release --strip -i '${{ steps.cpy.outputs.python-path }}'
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: python -m twine upload  "./target/wheels/*" --non-interactive --skip-existing